export const level2Questions = [
    // --- HEALTH (30 Questions) ---
    { text: "What is the primary function of carbohydrates?", options: ["Growth", "Energy", "Protection", "Storage"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which vitamin helps blood clotting?", options: ["Vitamin A", "Vitamin K", "Vitamin C", "Vitamin D"], answerIndex: 1, category: "Health", level: 2 },
    { text: "What is the main organ of the circulatory system?", options: ["Lungs", "Heart", "Kidney", "Brain"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Dehydration is caused by lack of?", options: ["Food", "Sleep", "Water", "Air"], answerIndex: 2, category: "Health", level: 2 },
    { text: "Which nutrient builds muscles?", options: ["Fats", "Protein", "Vitamins", "Carbs"], answerIndex: 1, category: "Health", level: 2 },
    { text: "How much sleep does a teenager need approx?", options: ["4-5 hrs", "8-10 hrs", "12-14 hrs", "2 hrs"], answerIndex: 1, category: "Health", level: 2 },
    { text: "What connects muscles to bones?", options: ["Ligaments", "Tendons", "Joints", "Nerves"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which disease is spread by polluted water?", options: ["Flu", "Cholera", "Malaria", "Cancer"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Normal heart rate for adults is?", options: ["20-30 bpm", "60-100 bpm", "100-150 bpm", "10-20 bpm"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which organ filters blood?", options: ["Heart", "Stomach", "Kidney", "Lungs"], answerIndex: 2, category: "Health", level: 2 },
    { text: "Which is a rich source of Iron?", options: ["Rice", "Spinach", "Sugar", "Oil"], answerIndex: 1, category: "Health", level: 2 },
    { text: "What causes cavities in teeth?", options: ["Calcium", "Bacteria and acid", "Water", "Saliva"], answerIndex: 1, category: "Health", level: 2 },
    { text: "CPR stands for?", options: ["Cardio Pulmonary Resuscitation", "Call Police Rapidly", "Check Pulse Rhythmic", "Cardiac Press Repeat"], answerIndex: 0, category: "Health", level: 2 },
    { text: "Which is a communicable disease?", options: ["Diabetes", "Influenza (Flu)", "Cancer", "Asthma"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Antibiotics are used to fight?", options: ["Viruses", "Bacteria", "Fungi", "Pain"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which harmful UV rays come from sun?", options: ["Gamma", "Ultraviolet (UV)", "X-Ray", "Infrared"], answerIndex: 1, category: "Health", level: 2 },
    { text: "BMI measures?", options: ["Intelligence", "Body Fat based on height/weight", "Strength", "Flexibility"], answerIndex: 1, category: "Health", level: 2 },
    { text: "The skeleton protects the?", options: ["Skin", "Organs", "Hair", "Clothes"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Vaccines protect us from?", options: ["Accidents", "Diseases", "Hunger", "Thirst"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which gas is bad for health to breathe?", options: ["Oxygen", "Carbon Monoxide", "Nitrogen", "Argon"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Normal blood pressure is around?", options: ["120/80", "150/100", "90/50", "200/100"], answerIndex: 0, category: "Health", level: 2 },
    { text: "Stress can be reduced by?", options: ["Meditation", "Smoking", "Yelling", "Eating junk"], answerIndex: 0, category: "Health", level: 2 },
    { text: "Fiber in food helps in?", options: ["Seeing", "Digestion", "Thinking", "Running"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which part of the brain controls balance?", options: ["Cerebrum", "Cerebellum", "Brain Stem", "Medulla"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Lack of Iodine causes?", options: ["Goitre", "Rickets", "Night Blindness", "Beriberi"], answerIndex: 0, category: "Health", level: 2 },
    { text: "Which blood cells fight infection?", options: ["RBC", "WBC", "Platelets", "Plasma"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Malaria is spread by?", options: ["Male Mosquito", "Female Anopheles Mosquito", "Housefly", "Rat"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which organ produce bile?", options: ["Pancreas", "Liver", "Kidney", "Stomach"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Insulin controls?", options: ["Heart rate", "Blood Sugar", "Digestion", "Growth"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Richest source of Vitamin C?", options: ["Milk", "Amla/Citrus", "Meat", "Bread"], answerIndex: 1, category: "Health", level: 2 },

    // --- SCIENCE (30 Questions) ---
    { text: "Chemical formula of Common Salt?", options: ["H2O", "NaCl", "HCl", "CO2"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Force is measured in?", options: ["Joules", "Newtons", "Watts", "Meters"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which planet is the Hottest?", options: ["Mercury", "Venus", "Mars", "Jupiter"], answerIndex: 1, category: "Science", level: 2 },
    { text: "What is the pH of pure water?", options: ["5", "7", "9", "0"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which metal rusts?", options: ["Gold", "Iron", "Aluminum", "Silver"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Speed of sound is max in?", options: ["Vacuum", "Air", "Water", "Solid (Steel)"], answerIndex: 3, category: "Science", level: 2 },
    { text: "Photosynthesis uses?", options: ["O2", "CO2", "N2", "He"], answerIndex: 1, category: "Science", level: 2 },
    { text: "The unit of Frequency?", options: ["Second", "Hertz", "Meter", "Pascal"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Electrons have what charge?", options: ["Positive", "Negative", "Neutral", "None"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which mirror shows a virtual, erect, and same-sized image?", options: ["Concave", "Convex", "Plane", "Parabolic"], answerIndex: 2, category: "Science", level: 2 },
    { text: "Who discovered Gravity (Apple)?", options: ["Einstein", "Newton", "Tesla", "Galileo"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which gas supports combustion?", options: ["Nitrogen", "Oxygen", "CO2", "Hydrogen"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Human body has how many bones (Adult)?", options: ["100", "206", "300", "500"], answerIndex: 1, category: "Science", level: 2 },
    { text: "The smallest unit of life?", options: ["Tissue", "Cell", "Organ", "Atom"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which acid is in lemon?", options: ["Citric Acid", "Acetic Acid", "Lactic Acid", "Hydrochloric Acid"], answerIndex: 0, category: "Science", level: 2 },
    { text: "Heat flows from?", options: ["Cold to Hot", "Hot to Cold", "Same to Same", "Doesn't flow"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which is a noble gas?", options: ["Oxygen", "Helium", "Hydrogen", "Nitrogen"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Rusting of iron is a ____ change.", options: ["Physical", "Chemical", "Biological", "Magnetic"], answerIndex: 1, category: "Science", level: 2 },
    { text: "What measures electric current?", options: ["Voltmeter", "Ammeter", "Thermometer", "Barometer"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Ozone layer protects us from?", options: ["Rain", "UV Radiation", "Asteroids", "Cold"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Milk turning sour is due to?", options: ["Virus", "Bacteria", "Fungi", "Protozoa"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Light travels faster than?", options: ["Everything", "Sound", "Rocket", "All of these"], answerIndex: 3, category: "Science", level: 2 },
    { text: "Dry Ice is solid ____?", options: ["Water", "Carbon Dioxide", "Nitrogen", "Oxygen"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which force stops a moving ball?", options: ["Gravity", "Friction", "Magnetic", "Electrostatic"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Fossil fuels are?", options: ["Renewable", "Non-renewable", "Infinite", "Artificial"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Greenhouse gas example?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], answerIndex: 1, category: "Science", level: 2 },
    { text: "A solution with pH 2 is?", options: ["Neutral", "Basic", "Acidic", "Salty"], answerIndex: 2, category: "Science", level: 2 },
    { text: "Which blood group is Universal Acceptor?", options: ["O-", "A+", "AB+", "B-"], answerIndex: 2, category: "Science", level: 2 },
    { text: "Electric bulb filament is made of?", options: ["Copper", "Tungsten", "Silver", "Iron"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Sound travels fastest in?", options: ["Gas", "Liquid", "Solid", "Vacuum"], answerIndex: 2, category: "Science", level: 2 },

    // --- SPORTS (30 Questions) ---
    { text: "Dhyan Chand is associated with?", options: ["Cricket", "Hockey", "Football", "Chess"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "How long is a Football match?", options: ["60 mins", "90 mins", "100 mins", "120 mins"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Which country hosts Wimbledon?", options: ["USA", "France", "UK (England)", "Australia"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "Butterfly stroke is used in?", options: ["Tennis", "Swimming", "Cricket", "Painting"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Term 'Googly' is used in?", options: ["Cricket", "Football", "Hockey", "Golf"], answerIndex: 0, category: "Sports", level: 2 },
    { text: "Who is 'The Wall' in Cricket?", options: ["Dravid", "Tendulkar", "Kohli", "Dhoni"], answerIndex: 0, category: "Sports", level: 2 },
    { text: "NBA is related to?", options: ["Baseball", "Basketball", "Bowling", "Boxing"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Which game uses a Shuttlecock?", options: ["Tennis", "Badminton", "Squash", "Polo"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "How many squares on a Chess board?", options: ["60", "62", "64", "66"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "Eden Gardens is in?", options: ["Mumbai", "Kolkata", "Delhi", "Chennai"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "FIFA World Cup is every ____ years.", options: ["2", "3", "4", "5"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "Who holds record for 100m sprint?", options: ["Lewis", "Bolt", "Gatlin", "Blake"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Prakash Padukone played?", options: ["Tennis", "Badminton", "Cricket", "Hockey"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Term 'Ace' is used in?", options: ["Cricket", "Tennis", "Football", "Hockey"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Yellow Card is a warning in?", options: ["Cricket", "Football", "Chess", "Carrom"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "IPL stands for?", options: ["Indian Premier League", "International Pro League", "Indian Players League", "India Pakistan League"], answerIndex: 0, category: "Sports", level: 2 },
    { text: "Sania Mirza plays?", options: ["Badminton", "Tennis", "Cricket", "Hockey"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Maximum score in Ten Pin Bowling?", options: ["100", "200", "300", "500"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "The Ashes is played between?", options: ["India-Pak", "Aus-Eng", "SA-Aus", "Eng-Ind"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Gully position is in?", options: ["Cricket", "Football", "Hockey", "Golf"], answerIndex: 0, category: "Sports", level: 2 },
    { text: "Which is not an Olympic sport?", options: ["Swimming", "Football", "Cricket (until recently)", "Athletics"], answerIndex: 2, category: "Sports", level: 2 }, // Cricket is returning but traditionally answer
    { text: "Tiger Woods plays?", options: ["Tennis", "Golf", "Pool", "Cards"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Viswanathan Anand plays?", options: ["Carrom", "Chess", "Ludo", "Monopoly"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "How many players in Kabaddi team (on court)?", options: ["5", "6", "7", "8"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "Deepa Malik is a?", options: ["Swimmer", "Paralympian (Athlete)", "Cricketer", "Actor"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Which sport has a 'Penalty Corner'?", options: ["Football", "Hockey", "Tennis", "Basketball"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Leander Paes plays?", options: ["Singles", "Doubles Tennis", "Cricket", "Golf"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Which ring color represents Asia in Olympics?", options: ["Blue", "Yellow", "Black", "Green"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Standard Golf course has ____ holes.", options: ["9", "12", "18", "20"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "Who is 'Captain Cool'?", options: ["Kohli", "Dhoni", "Ganguly", "Rohit"], answerIndex: 1, category: "Sports", level: 2 },

    // --- GK (30 Questions) ---
    { text: "Currency of Japan?", options: ["Yuan", "Won", "Yen", "Dollar"], answerIndex: 2, category: "GK", level: 2 },
    { text: "Capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], answerIndex: 2, category: "GK", level: 2 },
    { text: "Who invented the Telephone?", options: ["Edison", "Bell", "Marconi", "Newton"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Which continent is darkest?", options: ["Asia", "Africa", "Europe", "Australia"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Largest freshwater lake?", options: ["Caspian", "Superior", "Victoria", "Baikal"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Who wrote 'Harry Potter'?", options: ["J.K. Rowling", "Roald Dahl", "Ruskin Bond", "Enid Blyton"], answerIndex: 0, category: "GK", level: 2 },
    { text: "Longest river in India?", options: ["Yamuna", "Ganga", "Godavari", "Cauvery"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Smallest country in the world?", options: ["Monaco", "Vatican City", "Maldives", "Nepal"], answerIndex: 1, category: "GK", level: 2 },
    { text: "National Flower of India?", options: ["Rose", "Lotus", "Tulip", "Sunflower"], answerIndex: 1, category: "GK", level: 2 },
    { text: "First woman in space?", options: ["Kalpana Chawla", "Valentina Tereshkova", "Sunita Williams", "Sally Ride"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Land of White Elephants?", options: ["India", "Thailand", "Africa", "China"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Highest mountain peak?", options: ["K2", "Everest", "Kangchenjunga", "Makalu"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Capital of China?", options: ["Shanghai", "Beijing", "Hong Kong", "Wuhan"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Full form of Wi-Fi?", options: ["Wireless Fidelity", "Wireless Find", "Wire Fire", "World Fi"], answerIndex: 0, category: "GK", level: 2 },
    { text: "Who founded Microsoft?", options: ["Jobs", "Gates", "Musk", "Zuckerberg"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Statue of Liberty is in?", options: ["Paris", "London", "New York", "Washington"], answerIndex: 2, category: "GK", level: 2 },
    { text: "National Tree of India?", options: ["Neem", "Peepal", "Banyan", "Mango"], answerIndex: 2, category: "GK", level: 2 },
    { text: "Which bird lays largest egg?", options: ["Emu", "Ostrich", "Eagle", "Penguin"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Who is 'Iron Man of India'?", options: ["Gandhi", "Patel", "Nehru", "Bose"], answerIndex: 1, category: "GK", level: 2 },
    { text: "How many states in India?", options: ["25", "28", "29", "30"], answerIndex: 1, category: "GK", level: 2 }, // Current count 28
    { text: "Symbol of Peace?", options: ["Rose", "Dove", "Eagle", "Lion"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Language spoken in Brazil?", options: ["Spanish", "French", "Portuguese", "English"], answerIndex: 2, category: "GK", level: 2 },
    { text: "World's largest rainforest?", options: ["Congo", "Amazon", "Sundarbans", "Daintree"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Who painted 'Starry Night'?", options: ["Picasso", "Van Gogh", "Da Vinci", "Monet"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Eiffel Tower is in?", options: ["London", "Rome", "Paris", "Berlin"], answerIndex: 2, category: "GK", level: 2 },
    { text: "Hardest substance?", options: ["Gold", "Iron", "Diamond", "Stone"], answerIndex: 2, category: "GK", level: 2 },
    { text: "How many zeros in one million?", options: ["5", "6", "9", "3"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Capital of UK?", options: ["London", "Paris", "Dublin", "Edinburgh"], answerIndex: 0, category: "GK", level: 2 },
    { text: "Fastest bird?", options: ["Eagle", "Falcon", "Hawk", "Ostrich"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Who invented the Airplane?", options: ["Bell", "Edison", "Wright Brothers", "Ford"], answerIndex: 2, category: "GK", level: 2 },

    // --- HISTORY (30 Questions) ---
    { text: "Who was the first Mughal Emperor?", options: ["Akbar", "Babur", "Humayun", "Shah Jahan"], answerIndex: 1, category: "History", level: 2 },
    { text: "Battle of Plassey year?", options: ["1757", "1857", "1947", "1526"], answerIndex: 0, category: "History", level: 2 },
    { text: "Quit India Movement year?", options: ["1920", "1930", "1942", "1947"], answerIndex: 2, category: "History", level: 2 },
    { text: "Who wrote the Ramayana?", options: ["Valmiki", "Veda Vyasa", "Tulsidas", "Kalidasa"], answerIndex: 0, category: "History", level: 2 },
    { text: "Last Viceroy of India?", options: ["Curzon", "Dalhousie", "Mountbatten", "Canning"], answerIndex: 2, category: "History", level: 2 },
    { text: "Founder of Sikhism?", options: ["Guru Gobind Singh", "Guru Nanak Dev", "Guru Arjan Dev", "Guru Tegh Bahadur"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who built the Red Fort?", options: ["Akbar", "Shah Jahan", "Jahangir", "Aurangzeb"], answerIndex: 1, category: "History", level: 2 },
    { text: "Capital of Ashoka's empire?", options: ["Pataliputra", "Taxila", "Ujjain", "Kalinga"], answerIndex: 0, category: "History", level: 2 },
    { text: "Jallianwala Bagh massacre year?", options: ["1919", "1920", "1922", "1915"], answerIndex: 0, category: "History", level: 2 },
    { text: "Who founded the 'Azad Hind Fauj'?", options: ["Gandhi", "Nehru", "Bose", "Bhagat Singh"], answerIndex: 2, category: "History", level: 2 },
    { text: "First War of Independence?", options: ["1857", "1947", "1905", "1757"], answerIndex: 0, category: "History", level: 2 },
    { text: "Who was the 'Frontier Gandhi'?", options: ["Jinnah", "Khan Abdul Ghaffar Khan", "Liaquat Ali", "Azad"], answerIndex: 1, category: "History", level: 2 },
    { text: "Vasco da Gama came to India in?", options: ["1492", "1498", "1526", "1600"], answerIndex: 1, category: "History", level: 2 },
    { text: "The Great Bath was found in?", options: ["Harappa", "Mohenjo-Daro", "Lothal", "Kalibangan"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who gave the slogan 'Do or Die'?", options: ["Nehru", "Gandhi", "Bose", "Tilak"], answerIndex: 1, category: "History", level: 2 },
    { text: "First lady Prime Minister of India?", options: ["Sarojini Naidu", "Indira Gandhi", "Pratibha Patil", "Sonia Gandhi"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who wrote 'Vande Mataram'?", options: ["Tagore", "Bankim Chandra", "Iqbal", "Prasad"], answerIndex: 1, category: "History", level: 2 },
    { text: "Aryabhata was a famous?", options: ["King", "Doctor", "Astronomer/Mathematician", "Poet"], answerIndex: 2, category: "History", level: 2 },
    { text: "Who built the Grand Trunk Road?", options: ["Akbar", "Sher Shah Suri", "Ashoka", "British"], answerIndex: 1, category: "History", level: 2 },
    { text: "Constitution was adopted on?", options: ["Aug 15 1947", "Jan 26 1950", "Nov 26 1949", "Oct 2 1948"], answerIndex: 2, category: "History", level: 2 },
    { text: "Rani Padmini was queen of?", options: ["Jaipur", "Chittorgarh", "Udaipur", "Jodhpur"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who was 'Lokmanya'?", options: ["Tilak", "Gokhale", "Gandhi", "Patel"], answerIndex: 0, category: "History", level: 2 },
    { text: "Sati Pratha was banned by?", options: ["Dalhousie", "Bentinck", "Curzon", "Ripon"], answerIndex: 1, category: "History", level: 2 },
    { text: "First Battle of Panipat?", options: ["1526", "1556", "1761", "1576"], answerIndex: 0, category: "History", level: 2 },
    { text: "Who wrote the Mahabharata?", options: ["Valmiki", "Veda Vyasa", "Tulsidas", "Surdas"], answerIndex: 1, category: "History", level: 2 },
    { text: "Din-i-Ilahi was founded by?", options: ["Babur", "Akbar", "Shah Jahan", "Aurangzeb"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who is known as 'Napoleon of India'?", options: ["Ashoka", "Samudragupta", "Chandragupta", "Harsha"], answerIndex: 1, category: "History", level: 2 },
    { text: "Golden Age of Ancient India?", options: ["Maurya", "Gupta", "Mughal", "British"], answerIndex: 1, category: "History", level: 2 },
    { text: "Tipu Sultan was ruler of?", options: ["Hyderabad", "Mysore", "Bengal", "Maratha"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who said 'Swaraj is my birthright'?", options: ["Gandhi", "Tilak", "Bose", "Lala Lajpat Rai"], answerIndex: 1, category: "History", level: 2 },
];
