export const questionBank = [
    // --- LEVEL 1 (Classes 4-6) ---
    // GK
    { text: "Which is the largest planet in our solar system?", options: ["Earth", "Mars", "Jupiter", "Saturn"], answerIndex: 2, category: "GK", level: 1 },
    { text: "What color is a school bus?", options: ["Red", "Yellow", "Blue", "Green"], answerIndex: 1, category: "GK", level: 1 },
    { text: "How many days are in a year?", options: ["360", "364", "365", "366"], answerIndex: 2, category: "GK", level: 1 },
    { text: "What is the capital of India?", options: ["Mumbai", "Kolkata", "Delhi", "Chennai"], answerIndex: 2, category: "GK", level: 1 },
    { text: "Which animal is known as the 'Ship of the Desert'?", options: ["Horse", "Camel", "Elephant", "Donkey"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which festival is known as the 'Festival of Colors'?", options: ["Diwali", "Holi", "Eid", "Christmas"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which is the tallest animal on Earth?", options: ["Elephant", "Giraffe", "Ostrich", "Zebra"], answerIndex: 1, category: "GK", level: 1 },
    { text: "What is the name of our galaxy?", options: ["Andromeda", "Milky Way", "Orion", "Centaurus"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which fruit is known as the 'King of Fruits' in India?", options: ["Apple", "Mango", "Banana", "Grape"], answerIndex: 1, category: "GK", level: 1 },
    { text: "How many colors are in a rainbow?", options: ["5", "6", "7", "8"], answerIndex: 2, category: "GK", level: 1 },

    // Science
    { text: "Which gas do humans breathe in to live?", options: ["Nitrogen", "Carbon Dioxide", "Oxygen", "Hydrogen"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Plants make their own food using what?", options: ["Moonlight", "Sunlight", "Starlight", "Firelight"], answerIndex: 1, category: "Science", level: 1 },
    { text: "What is the solid form of water called?", options: ["Vapor", "Liquid", "Ice", "Mist"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Which part of the plant grows underground?", options: ["Stem", "Leaf", "Flower", "Root"], answerIndex: 3, category: "Science", level: 1 },
    { text: "What orbits the Earth?", options: ["Sun", "Moon", "Mars", "Jupiter"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Which sense organ is used for hearing?", options: ["Nose", "Eyes", "Ears", "Tongue"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Which animal says 'Meow'?", options: ["Dog", "Cat", "Cow", "Lion"], answerIndex: 1, category: "Science", level: 1 },
    { text: "How many legs does a spider have?", options: ["4", "6", "8", "10"], answerIndex: 2, category: "Science", level: 1 },
    { text: "What does the sun provide us?", options: ["Water", "Food", "Heat and Light", "Air"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Frogs are born from what?", options: ["Seeds", "Eggs", "Flowers", "Leaves"], answerIndex: 1, category: "Science", level: 1 },

    // Health
    { text: "How many times should we brush our teeth daily?", options: ["Once", "Twice", "Three times", "Never"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Which vitamin do we get from the morning sun?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], answerIndex: 3, category: "Health", level: 1 },
    { text: "Drinking what helps make our bones strong?", options: ["Soda", "Juice", "Milk", "Coffee"], answerIndex: 2, category: "Health", level: 1 },
    { text: "What should we use to wash our hands before eating?", options: ["Only Water", "Soap and Water", "Towel", "Paper"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Which fruit an apple a day keeps the ____ away?", options: ["Teacher", "Doctor", "Friend", "Dentist"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Where should we throw garbage?", options: ["On the road", "In the Dustbin", "Under the bed", "Out of window"], answerIndex: 1, category: "Health", level: 1 },
    { text: "What part of the body do we use to think?", options: ["Heart", "Stomach", "Brain", "Lungs"], answerIndex: 2, category: "Health", level: 1 },
    { text: "Sleep is important for what?", options: ["Growing", "Running", "Dancing", "Crying"], answerIndex: 0, category: "Health", level: 1 },
    { text: "Which activity keeps our body active and healthy?", options: ["Watching TV", "Sleeping all day", "Exercise", "Eating junk food"], answerIndex: 2, category: "Health", level: 1 },
    { text: "What counts as a healthy snack?", options: ["Chips", "Candy", "Apple", "Chocolate"], answerIndex: 2, category: "Health", level: 1 },

    // History
    { text: "Who is known as the 'Father of the Nation' in India?", options: ["Jawaharlal Nehru", "Subhash Chandra Bose", "Mahatma Gandhi", "Bhagat Singh"], answerIndex: 2, category: "History", level: 1 },
    { text: "When did India get independence?", options: ["1942", "1947", "1950", "1952"], answerIndex: 1, category: "History", level: 1 },
    { text: "Who was the first female Prime Minister of India?", options: ["Pratibha Patil", "Sarojini Naidu", "Indira Gandhi", "Sushma Swaraj"], answerIndex: 2, category: "History", level: 1 },
    { text: "Which monument is also known as the 'Symbol of Love'?", options: ["Red Fort", "Qutub Minar", "Taj Mahal", "Golden Temple"], answerIndex: 2, category: "History", level: 1 },
    { text: "Who was the first citizen of India?", options: ["Prime Minister", "President", "Chief Justice", "Governor"], answerIndex: 1, category: "History", level: 1 },
    { text: "Ashoka was a great king of which dynasty?", options: ["Mughal", "Gupta", "Maurya", "Chola"], answerIndex: 2, category: "History", level: 1 },
    { text: "What is the color of the wheel (Chakra) in the Indian flag?", options: ["Blue", "Black", "Green", "Red"], answerIndex: 0, category: "History", level: 1 },
    { text: "Who built the Taj Mahal?", options: ["Akbar", "Shah Jahan", "Aurangzeb", "Babur"], answerIndex: 1, category: "History", level: 1 },
    { text: "Which freedom fighter gave the slogan 'Jai Hind'?", options: ["Gandhiji", "Nehru ji", "Subhash Chandra Bose", "Bhagat Singh"], answerIndex: 2, category: "History", level: 1 },
    { text: "The capital of Mughal Empire under Akbar was?", options: ["Delhi", "Agra", "Fatehpur Sikri", "Lahore"], answerIndex: 2, category: "History", level: 1 },

    // Sports
    { text: "Which game is MS Dhoni associated with?", options: ["Hockey", "Tennis", "Cricket", "Football"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "How many players are in a cricket team on the field?", options: ["10", "11", "12", "9"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Which sport is played with a racket and a shuttlecock?", options: ["Tennis", "Table Tennis", "Badminton", "Squash"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Who is known as the 'Master Blaster'?", options: ["Virat Kohli", "Sourav Ganguly", "Sachin Tendulkar", "Sunil Gavaskar"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "In which sport do you use the term 'Checkmate'?", options: ["Ludo", "Chess", "Carrom", "Cards"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Which city hosted the first Olympic Games?", options: ["London", "Paris", "Athens", "Rome"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Which game uses the term 'LBW'?", options: ["Football", "Hockey", "Cricket", "Rugby"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Sunil Chhetri is a famous Indian player of which sport?", options: ["Cricket", "Football", "Hockey", "Tennis"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Which of these is an indoor game?", options: ["Football", "Cricket", "Chess", "Hockey"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "How many rings are there in the Olympic flag?", options: ["4", "5", "6", "3"], answerIndex: 1, category: "Sports", level: 1 },

    // --- LEVEL 2 (Classes 7-8) ---
    // GK
    { text: "Which is the longest river in the world?", options: ["Amazon", "Nile", "Ganga", "Yangtze"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Who wrote 'Discovery of India'?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "Rabindranath Tagore"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Which country is called the 'Land of Rising Sun'?", options: ["China", "Japan", "Norway", "Australia"], answerIndex: 1, category: "GK", level: 2 },
    { text: "What is the currency of USA?", options: ["Euro", "Pound", "Dollar", "Yen"], answerIndex: 2, category: "GK", level: 2 },
    { text: "Who is the CEO of Google (Alphabet)?", options: ["Satya Nadella", "Sundar Pichai", "Tim Cook", "Elon Musk"], answerIndex: 1, category: "GK", level: 2 },
    { text: "Which is the largest desert in the world?", options: ["Thar", "Gobi", "Sahara", "Antarctica"], answerIndex: 3, category: "GK", level: 2 },
    { text: "World Environment Day is celebrated on?", options: ["July 5", "June 5", "May 5", "August 5"], answerIndex: 1, category: "GK", level: 2 },
    { text: "The headquarters of ISRO is in?", options: ["Mumbai", "Chennai", "Bengaluru", "Delhi"], answerIndex: 2, category: "GK", level: 2 },
    { text: "Who was the architect of Indian Constitution?", options: ["Nehru", "Gandhiji", "B.R. Ambedkar", "Patel"], answerIndex: 2, category: "GK", level: 2 },
    { text: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answerIndex: 1, category: "GK", level: 2 },

    // Science
    { text: "What is the chemical formula for water?", options: ["CO2", "H2O", "O2", "NaCl"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Which gas is filled in balloons that float?", options: ["Helium", "Oxygen", "Nitrogen", "Argon"], answerIndex: 0, category: "Science", level: 2 },
    { text: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Lysosome"], answerIndex: 2, category: "Science", level: 2 },
    { text: "Which metal is liquid at room temperature?", options: ["Iron", "Mercury", "Gold", "Silver"], answerIndex: 1, category: "Science", level: 2 },
    { text: "What is the boiling point of water in Celsius?", options: ["50", "100", "150", "200"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Light travels in a ____ line.", options: ["Curved", "Zigzag", "Straight", "Circular"], answerIndex: 2, category: "Science", level: 2 },
    { text: "Which star is closest to the Earth?", options: ["Proxima Centauri", "Sirius", "Sun", "Polaris"], answerIndex: 2, category: "Science", level: 2 },
    { text: "What is the hardest natural substance?", options: ["Gold", "Diamond", "Platinum", "Iron"], answerIndex: 1, category: "Science", level: 2 },
    { text: "Sound cannot travel through ____.", options: ["Water", "Air", "Vacuum", "Steel"], answerIndex: 2, category: "Science", level: 2 },
    { text: "Scurvy is caused by deficiency of Vitamin ____.", options: ["A", "B", "C", "D"], answerIndex: 2, category: "Science", level: 2 },

    // Health
    { text: "Which organ in the human body produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Spleen"], answerIndex: 1, category: "Health", level: 2 },
    { text: "What is the normal body temperature of a human in Fahrenheit?", options: ["96.6", "98.6", "100.6", "102.6"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which component of blood helps in clotting?", options: ["WBC", "RBC", "Platelets", "Plasma"], answerIndex: 2, category: "Health", level: 2 },
    { text: "Protein deficiency causes which disease?", options: ["Scurvy", "Marasmus/Kwashiorkor", "Rickets", "Anemia"], answerIndex: 1, category: "Health", level: 2 },
    { text: "What is the largest organ in the human body?", options: ["Liver", "Skin", "Lungs", "Small Intestine"], answerIndex: 1, category: "Health", level: 2 },
    { text: "Which bone is the longest in the human body?", options: ["Spine", "Femur", "Humerus", "Tibia"], answerIndex: 1, category: "Health", level: 2 },
    { text: "What is the primary function of white blood cells?", options: ["Carry Oxygen", "Fight Infection", "Heal Wounds", "Digest Food"], answerIndex: 1, category: "Health", level: 2 },
    { text: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], answerIndex: 2, category: "Health", level: 2 },
    { text: "Anaemia is caused by the deficiency of?", options: ["Iodine", "Iron", "Calcium", "Magnesium"], answerIndex: 1, category: "Health", level: 2 },
    { text: "What does BMI stand for?", options: ["Body Mass Index", "Basic Metabolic Intake", "Body Muscle Intensity", "Basic Muscle Index"], answerIndex: 0, category: "Health", level: 2 },

    // History
    { text: "The 'Dandi March' was started by Gandhiji to protest against?", options: ["Land tax", "Salt tax", "Cloth tax", "Indigo farming"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who was the first Mughal Emperor of India?", options: ["Akbar", "Humayun", "Babur", "Shah Jahan"], answerIndex: 2, category: "History", level: 2 },
    { text: "The Battle of Plassey was fought in?", options: ["1757", "1764", "1857", "1526"], answerIndex: 0, category: "History", level: 2 },
    { text: "Who gave the title 'Mahatma' to Gandhiji?", options: ["Nehru", "Tagore", "Patel", "Tilak"], answerIndex: 1, category: "History", level: 2 },
    { text: "Which city was the capital of Vijayanagara Empire?", options: ["Madurai", "Hampi", "Mysuru", "Thanjavur"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who was the first Governor-General of independent India?", options: ["Lord Mountbatten", "C. Rajagopalachari", "Nehru", "Radhakrishnan"], answerIndex: 0, category: "History", level: 2 },
    { text: "In which year did the First World War begin?", options: ["1912", "1914", "1918", "1939"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who was known as the 'Light of Asia'?", options: ["Mahavira", "Gautama Buddha", "Ashoka", "Akbar"], answerIndex: 1, category: "History", level: 2 },
    { text: "The Vedas are written in which language?", options: ["Pali", "Sanskrit", "Hindi", "Prakrit"], answerIndex: 1, category: "History", level: 2 },
    { text: "Who founded the Brahmo Samaj?", options: ["Dayanand Saraswati", "Vivekananda", "Raja Ram Mohan Roy", "Ishwar Chandra Vidyasagar"], answerIndex: 2, category: "History", level: 2 },

    // Sports
    { text: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "Italy"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "Usain Bolt is a legendary athlete in which event?", options: ["Swimming", "Sprinting", "Long Jump", "Cycling"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "The term 'Hat-trick' is used in?", options: ["Cricket", "Football", "Hockey", "All of these"], answerIndex: 3, category: "Sports", level: 2 },
    { text: "Who won the first individual Olympic Gold for India?", options: ["Neeraj Chopra", "Abhinav Bindra", "P.V. Sindhu", "Mary Kom"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "How long is a standard Marathon race?", options: ["21 km", "42.195 km", "50 km", "10 km"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "In which sport is the 'Davis Cup' awarded?", options: ["Tennis", "Golf", "Polo", "Badminton"], answerIndex: 0, category: "Sports", level: 2 },
    { text: "The 'Thomas Cup' is associated with which sport?", options: ["Cricket", "Badminton", "Tennis", "Table Tennis"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Who is the first Indian woman to win an Olympic medal?", options: ["P.T. Usha", "Karnam Malleswari", "Saina Nehwal", "Mary Kom"], answerIndex: 1, category: "Sports", level: 2 },
    { text: "Which ground is known as the 'Mecca of Cricket'?", options: ["MCG", "Eden Gardens", "Lord's", "The Oval"], answerIndex: 2, category: "Sports", level: 2 },
    { text: "How many players are there on a basketball court for one team?", options: ["5", "6", "7", "11"], answerIndex: 0, category: "Sports", level: 2 },

    // --- LEVEL 3 (Classes 9-10) ---
    // GK
    { text: "Which international organization is responsible for global health?", options: ["UNICEF", "UNESCO", "WHO", "WTO"], answerIndex: 2, category: "GK", level: 3 },
    { text: "What is the retirement age of a Supreme Court judge in India?", options: ["60", "62", "65", "11"], answerIndex: 2, category: "GK", level: 3 },
    { text: "Who is the current Secretary-General of the United Nations?", options: ["Ban Ki-moon", "Kofi Annan", "Antonio Guterres", "Tedros Adhanom"], answerIndex: 2, category: "GK", level: 3 },
    { text: "Which Indian state has the longest coastline?", options: ["Tamil Nadu", "Maharashtra", "Gujarat", "Andhra Pradesh"], answerIndex: 2, category: "GK", level: 3 },
    { text: "What is the full form of GDP?", options: ["Gross Domestic Provision", "General Domestic Product", "Gross Domestic Product", "Gross Daily Production"], answerIndex: 2, category: "GK", level: 3 },
    { text: "Who was the first Indian to win the Nobel Prize?", options: ["C.V. Raman", "Mother Teresa", "Rabindranath Tagore", "Hargobind Khorana"], answerIndex: 2, category: "GK", level: 3 },
    { text: "The Fundamental Rights in India are borrowed from which country?", options: ["UK", "USA", "Canada", "Ireland"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Which pass connects Srinagar to Leh?", options: ["Zoji La", "Rohtang", "Nathu La", "Shipki La"], answerIndex: 0, category: "GK", level: 3 },
    { text: "Who is known as the 'Missile Man' of India?", options: ["Homi Bhabha", "Vikram Sarabhai", "A.P.J. Abdul Kalam", "Satish Dhawan"], answerIndex: 2, category: "GK", level: 3 },
    { text: "The Silicon Valley of India is?", options: ["Mumbai", "Hyderabad", "Bengaluru", "Pune"], answerIndex: 2, category: "GK", level: 3 },

    // Science
    { text: "What is the value of Acceleration due to Gravity on Earth?", options: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "7.8 m/s²"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Which lens is used to correct Short-sightedness (Myopia)?", options: ["Convex", "Concave", "Bifocal", "Cylindrical"], answerIndex: 1, category: "Science", level: 3 },
    { text: "The process of change from solid to gas directly is?", options: ["Evaporation", "Sublimation", "Condensation", "Fusion"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Which isotope of Uranium is used in nuclear reactors?", options: ["U-238", "U-235", "U-234", "U-239"], answerIndex: 1, category: "Science", level: 3 },
    { text: "What is the SI unit of Electric Current?", options: ["Volt", "Ohm", "Ampere", "Watt"], answerIndex: 2, category: "Science", level: 3 },
    { text: "Which acid is present in gastric juice in the stomach?", options: ["Sulphuric Acid", "Nitric Acid", "Hydrochloric Acid", "Acetic Acid"], answerIndex: 2, category: "Science", level: 3 },
    { text: "Who discovered the laws of Inheritance?", options: ["Charles Darwin", "Gregor Mendel", "Lamarck", "Watson"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Speed of light in vacuum is approximately?", options: ["3 x 10^5 m/s", "3 x 10^8 m/s", "3 x 10^10 m/s", "3 x 10^6 m/s"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Diamond is an allotrope of?", options: ["Silicon", "Carbon", "Sulphur", "Phosphorus"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Which mirrors are used in car headlights?", options: ["Plane", "Convex", "Concave", "Cylindrical"], answerIndex: 2, category: "Science", level: 3 },

    // Health
    { text: "What is the temporary storage of urine in the body?", options: ["Kidney", "Ureter", "Urinary Bladder", "Urethra"], answerIndex: 2, category: "Health", level: 3 },
    { text: "Which part of the eye determines its color?", options: ["Cornea", "Iris", "Pupil", "Retina"], answerIndex: 1, category: "Health", level: 3 },
    { text: "What is the average lifespan of a Red Blood Cell?", options: ["60 days", "100 days", "120 days", "150 days"], answerIndex: 2, category: "Health", level: 3 },
    { text: "Which hormone is known as the 'Flight or Fight' hormone?", options: ["Insulin", "Thyroxine", "Adrenaline", "Estrogen"], answerIndex: 2, category: "Health", level: 3 },
    { text: "Universal donor blood group is?", options: ["A+", "B+", "AB+", "O-"], answerIndex: 3, category: "Health", level: 3 },
    { text: "Bile is stored in which organ?", options: ["Liver", "Gall Bladder", "Pancreas", "Stomach"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which mineral is required for healthy thyroid function?", options: ["Iron", "Calcium", "Iodine", "Potassium"], answerIndex: 2, category: "Health", level: 3 },
    { text: "Double circulation is found in which organism?", options: ["Fish", "Amphibian", "Reptile", "Mammal"], answerIndex: 3, category: "Health", level: 3 },
    { text: "Which chemical is responsible for muscle cramps?", options: ["Lactic Acid", "Citric Acid", "Acetic Acid", "Uric Acid"], answerIndex: 0, category: "Health", level: 3 },
    { text: "What is the anatomical term for the voice box?", options: ["Pharynx", "Larynx", "Trachea", "Bronchi"], answerIndex: 1, category: "Health", level: 3 },

    // History
    { text: "Who was the founder of the Indian National Congress?", options: ["W.C. Bonnerjee", "A.O. Hume", "Dadabhai Naoroji", "Annie Besant"], answerIndex: 1, category: "History", level: 3 },
    { text: "The Simon Commission was boycotted because?", options: ["It was too expensive", "No Indian member", "It recommended partition", "It delayed independence"], answerIndex: 1, category: "History", level: 3 },
    { text: "In which year was the partition of Bengal cancelled?", options: ["1905", "1907", "1911", "1919"], answerIndex: 2, category: "History", level: 3 },
    { text: "Who wrote 'The Spirit of Laws'?", options: ["Rousseau", "Montesquieu", "Voltaire", "John Locke"], answerIndex: 1, category: "History", level: 3 },
    { text: "The Treaty of Versailles ended which war?", options: ["American Civil War", "French Revolution", "World War I", "World War II"], answerIndex: 2, category: "History", level: 3 },
    { text: "Which incident led to the suspension of Non-Cooperation Movement?", options: ["Jallianwala Bagh", "Chauri Chaura", "Dandi March", "Simon Commission"], answerIndex: 1, category: "History", level: 3 },
    { text: "Who was the political guru of Mahatma Gandhi?", options: ["Gopal Krishna Gokhale", "Bal Gangadhar Tilak", "Lala Lajpat Rai", "Chittaranjan Das"], answerIndex: 0, category: "History", level: 3 },
    { text: "First battle of Panipat took place in?", options: ["1526", "1556", "1761", "1576"], answerIndex: 0, category: "History", level: 3 },
    { text: "Who founded the 'Ghadar Party'?", options: ["Bhagat Singh", "Lala Hardayal", "Subhash Bose", "V.D. Savarkar"], answerIndex: 1, category: "History", level: 3 },
    { text: "The French Revolution started in the year?", options: ["1776", "1789", "1804", "1815"], answerIndex: 1, category: "History", level: 3 },

    // Sports
    { text: "How many Gold medals has Usain Bolt won in Olympics?", options: ["6", "8", "9", "10"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Which tennis player has won the most Grand Slam titles (Men's)?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"], answerIndex: 2, category: "Sports", level: 3 },
    { text: "The 'Grandmaster' title is given in which sport?", options: ["Bridge", "Chess", "Golf", "Polo"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Where is the headquarters of FIFA located?", options: ["Paris", "Zurich", "London", "Munich"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Which Indian sportsperson is known as the 'Dhing Express'?", options: ["Hima Das", "Dutee Chand", "P.V. Sindhu", "Mary Kom"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "What is the standard width of a tennis court for singles?", options: ["8.23 m", "10.97 m", "12 m", "9.5 m"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "The 'Uber Cup' is associated with?", options: ["Men's Badminton", "Women's Badminton", "Table Tennis", "Golf"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Which swimmer has won the most Olympic medals ever?", options: ["Ian Thorpe", "Michael Phelps", "Mark Spitz", "Caeleb Dressel"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "How many players are in a Polo team?", options: ["4", "5", "6", "7"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "The 'Ryder Cup' is a famous trophy in which sport?", options: ["Cricket", "Football", "Golf", "Tennis"], answerIndex: 2, category: "Sports", level: 3 },
];
