export const level3Questions = [
    // --- HEALTH (30 Questions) ---
    { text: "What is the structural and functional unit of kidney?", options: ["Neuron", "Nephron", "Alveoli", "Villi"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which hormone regulates blood sugar levels?", options: ["Adrenaline", "Insulin", "Thyroxine", "Estrogen"], answerIndex: 1, category: "Health", level: 3 },
    { text: "The master gland of the human body is?", options: ["Thyroid", "Pituitary", "Adrenal", "Pancreas"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which component of blood transports oxygen?", options: ["Plasma", "Hemoglobin (RBC)", "Platelets", "WBC"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Deficiency of Vitamin D causes in adults?", options: ["Rickets", "Osteoporosis/Osteomalacia", "Scurvy", "Beriberi"], answerIndex: 1, category: "Health", level: 3 },
    { text: "What is the largest gland in the body?", options: ["Pancreas", "Liver", "Thyroid", "Pituitary"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which part of brain controls involuntary actions?", options: ["Cerebrum", "Cerebellum", "Medulla Oblongata", "Hypothalamus"], answerIndex: 2, category: "Health", level: 3 },
    { text: "AIDS is caused by?", options: ["Bacteria", "Virus (HIV)", "Fungi", "Protozoa"], answerIndex: 1, category: "Health", level: 3 },
    { text: "How many pairs of ribs are there in humans?", options: ["10", "12", "14", "8"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which blood group is Universal Donor?", options: ["A+", "B-", "O-", "AB+"], answerIndex: 2, category: "Health", level: 3 },
    { text: "Where does fertilization occur in humans?", options: ["Uterus", "Fallopian Tube", "Ovary", "Vagina"], answerIndex: 1, category: "Health", level: 3 },
    { text: "The enzyme Pepsine digests?", options: ["Starch", "Proteins", "Fats", "Vitamins"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which vitamin is water soluble?", options: ["Vitamin A", "Vitamin B and C", "Vitamin D", "Vitamin K"], answerIndex: 1, category: "Health", level: 3 },
    { text: "What is the pacemaker of the heart?", options: ["AV Node", "SA Node", "Bundle of His", "Purkinje Fibers"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Myopia is corrected by using?", options: ["Convex Lens", "Concave Lens", "Bifocal Lens", "Cylindrical Lens"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which vessel carries deoxygenated blood to lungs?", options: ["Aorta", "Pulmonary Artery", "Pulmonary Vein", "Vena Cava"], answerIndex: 1, category: "Health", level: 3 },
    { text: "The covering of the lungs is called?", options: ["Pericardium", "Pleura", "Meninges", "Capsule"], answerIndex: 1, category: "Health", level: 3 },
    { text: "During inhalation, the diaphragm moves?", options: ["Up", "Down/Flattens", "No movement", "Sideways"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Smallest bone in the human body?", options: ["Femur", "Stapes", "Tibia", "Radius"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which organ breaks down alcohol?", options: ["Kidney", "Liver", "Heart", "Lungs"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Antibodies are produced by?", options: ["RBC", "Lymphocytes (WBC)", "Platelets", "Plasma"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Normal pH of human blood?", options: ["6.5", "7.4", "8.2", "5.0"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Endocrine glands secrete?", options: ["Enzymes", "Hormones", "Sweat", "Saliva"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Which part of the eye is sensitive to light?", options: ["Cornea", "Retina", "Iris", "Lens"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Average gestation period in humans?", options: ["250 days", "280 days (9 months)", "300 days", "365 days"], answerIndex: 1, category: "Health", level: 3 },
    { text: "What is 'bad' cholesterol?", options: ["HDL", "LDL", "VLDL", "Triglycerides"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Typhoid is caused by?", options: ["Virus", "Bacteria (Salmonella)", "Fungi", "Protozoa"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Dialysis is used for failure of?", options: ["Heart", "Kidney", "Liver", "Lungs"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Hardest tissue in the body?", options: ["Bone", "Enamel", "Cartilage", "Muscle"], answerIndex: 1, category: "Health", level: 3 },
    { text: "Number of chromosomes in human cell?", options: ["23", "46 (23 pairs)", "48", "44"], answerIndex: 1, category: "Health", level: 3 },

    // --- SCIENCE (30 Questions) ---
    { text: "Newton's First Law is also called?", options: ["Law of Momentum", "Law of Inertia", "Law of Action-Reaction", "Law of Gravity"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Atomic number is equal to number of?", options: ["Neutrons", "Protons", "Electrons + Neutrons", "Protons + Neutrons"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Work done is zero when angle is?", options: ["0 degrees", "90 degrees", "180 degrees", "45 degrees"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Power is defined as?", options: ["Force x Distance", "Rate of doing work", "Mass x Velocity", "Energy x Time"], answerIndex: 1, category: "Science", level: 3 },
    { text: "SI unit of Resistance?", options: ["Volt", "Ampere", "Ohm", "Watt"], answerIndex: 2, category: "Science", level: 3 },
    { text: "Valency of Carbon is?", options: ["2", "4", "6", "8"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Gas used in extinguishing fire?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "H2"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Isotope of Carbon used in dating?", options: ["C-12", "C-14", "C-13", "C-16"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Ohm's Law formula?", options: ["V = I/R", "V = IR", "R = VI", "I = VR"], answerIndex: 1, category: "Science", level: 3 },
    { text: "The value of 'g' is maximum at?", options: ["Equator", "Poles", "Center of Earth", "Space"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Light year is a unit of?", options: ["Time", "Distance", "Speed", "Intensity"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Sulphuric Acid formula?", options: ["HCl", "H2SO4", "HNO3", "H2CO3"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Mitochondria is called?", options: ["Control center", "Powerhouse of cell", "Suicide bag", "Protein factory"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Which reaction releases energy?", options: ["Endothermic", "Exothermic", "Photochemical", "Displacement"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Device to convert AC to DC?", options: ["Transformer", "Rectifier", "Generator", "Motor"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Main constituent of Biogas?", options: ["Butane", "Methane", "Propane", "Ethane"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Avogadro's constant value?", options: ["6.022 x 10^23", "6.22 x 10^22", "9.8 x 10^10", "1.6 x 10^-19"], answerIndex: 0, category: "Science", level: 3 },
    { text: "Bauxite is ore of?", options: ["Iron", "Aluminum", "Copper", "Zinc"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Mirage is due to?", options: ["Reflection", "Total Internal Reflection", "Refraction", "Diffraction"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Modern Periodic Table is based on?", options: ["Atomic Mass", "Atomic Number", "Neutrons", "Density"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Escape velocity of Earth?", options: ["9.8 km/s", "11.2 km/s", "15 km/s", "20 km/s"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Bleaching Powder formula?", options: ["CaO", "Ca(OH)2", "CaOCl2", "CaCO3"], answerIndex: 2, category: "Science", level: 3 },
    { text: "Which lens corrects Hypermetropia?", options: ["Concave", "Convex", "Bifocal", "Plane"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Functional group of Alcohol?", options: ["-CHO", "-COOH", "-OH", "-CO-"], answerIndex: 2, category: "Science", level: 3 },
    { text: "Flemings Left Hand Rule gives direction of?", options: ["Current", "Magnetic Field", "Force/Motion", "Resistance"], answerIndex: 2, category: "Science", level: 3 },
    { text: "Alloy of Copper and Zinc?", options: ["Bronze", "Brass", "Steel", "Solder"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Most simple Hydrocarbon?", options: ["Ethane", "Methane", "Propane", "Butane"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Fuse wire has?", options: ["High MP", "Low Melting Point", "High Resistance", "Low Resistance"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Galvanization uses coating of?", options: ["Tin", "Zinc", "Silver", "Copper"], answerIndex: 1, category: "Science", level: 3 },
    { text: "Dry cell converts Chemical energy to?", options: ["Mechanical", "Electrical", "Heat", "Light"], answerIndex: 1, category: "Science", level: 3 },

    // --- SPORTS (30 Questions) ---
    { text: "Who won the first Cricket World Cup (1975)?", options: ["India", "West Indies", "Australia", "England"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Number of rings in Olympic logo representing continents?", options: ["4", "5", "6", "7"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "National Game of USA?", options: ["Football", "Baseball", "Basketball", "Rugby"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Term 'Bully' is used in?", options: ["Cricket", "Hockey", "Football", "Tennis"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "First Indian individual Olympic Gold Medalist?", options: ["P.V. Sindhu", "Abhinav Bindra", "Neeraj Chopra", "Sushil Kumar"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Length of a Cricket Pitch?", options: ["20 yards", "22 yards", "24 yards", "18 yards"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Who has most Olympic Golds in history?", options: ["Bolt", "Phelps", "Spitz", "Lewis"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Thomas Cup is associated with?", options: ["Men's Badminton", "Women's Badminton", "Tennis", "Table Tennis"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "Hopman Cup is related to?", options: ["Tennis", "Table Tennis", "Hockey", "Football"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "Highest civilian award in India?", options: ["Padma Shri", "Bharat Ratna", "Padma Vibhushan", "Arjuna Award"], answerIndex: 1, category: "Sports", level: 3 }, // Often given to sportspersons like Tendulkar
    { text: "Mary Kom belongs to which state?", options: ["Assam", "Manipur", "Mizoram", "Meghalaya"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "The term 'Stalemate' is used in?", options: ["Chess", "Cricket", "Hockey", "Boxing"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "Roger Federer belongs to?", options: ["USA", "Switzerland", "Spain", "Germany"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Which trophy is for Football?", options: ["Ranji Trophy", "Santosh Trophy", "Davis Cup", "Uber Cup"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Weight of a cricket ball is approx?", options: ["100g", "155-163g", "200g", "250g"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "First Asian Games held in?", options: ["Tokyo", "New Delhi (1951)", "Beijing", "Bangkok"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Who broke the 4-minute mile barrier first?", options: ["Roger Bannister", "Sebastian Coe", "Usain Bolt", "Carl Lewis"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "Rider Cup is associated with?", options: ["Golf", "Polo", "Horse Racing", "Motor Racing"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "Magnus Carlsen is a champion of?", options: ["Chess", "Tennis", "F1", "Golf"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "How many red balls in Snooker?", options: ["10", "15", "20", "12"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "'Libero' is a player in?", options: ["Football", "Volleyball", "Basketball", "Hockey"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "First woman to win a Nobel Prize?", options: ["Mother Teresa", "Marie Curie", "Jane Addams", "Malala"], answerIndex: 1, category: "Sports", level: 3 }, // GK question sneaking in, but fine
    { text: "Dronacharya Award is given to?", options: ["Players", "Coaches", "Umpires", "Media"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Wankhede Stadium is in?", options: ["Delhi", "Mumbai", "Kolkata", "Chennai"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Term 'Double Fault' is used in?", options: ["Cricket", "Tennis", "Squash", "Badminton"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Jesse Owens was a famous?", options: ["Swimmer", "Sprinter/Athlete", "Boxer", "Cricketer"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Standard height of Badminton net?", options: ["5 feet", "6 feet", "4 feet", "3 feet"], answerIndex: 0, category: "Sports", level: 3 },
    { text: "FIFA headquarters?", options: ["Paris", "Zurich", "London", "New York"], answerIndex: 1, category: "Sports", level: 3 },
    { text: "Most Grand Slams in Women's Tennis?", options: ["Serena Williams", "Steffi Graf", "Margaret Court", "Navratilova"], answerIndex: 2, category: "Sports", level: 3 },
    { text: "Which country invented Table Tennis?", options: ["China", "England", "Japan", "USA"], answerIndex: 1, category: "Sports", level: 3 },

    // --- GK (30 Questions) ---
    { text: "Which constitutional amendment added 'Fundamental Duties'?", options: ["42nd", "44th", "86th", "73rd"], answerIndex: 0, category: "GK", level: 3 },
    { text: "Headquarters of UN?", options: ["Geneva", "New York", "Paris", "Washington"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Who decides the Repo Rate in India?", options: ["RBI", "SBI", "Finance Ministry", "PMO"], answerIndex: 0, category: "GK", level: 3 },
    { text: "The theme of G20 summit 2023 in India?", options: ["One Earth One Family One Future", "Recover Together", "Global South", "Climate Action"], answerIndex: 0, category: "GK", level: 3 },
    { text: "Sunderbans is famous for?", options: ["Lions", "Royal Bengal Tigers", "Rhinos", "Elephants"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Which line divides India and China?", options: ["Radcliffe Line", "McMahon Line", "Durand Line", "Palk Strait"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Who appoints the Governor of a state?", options: ["CM", "President", "PM", "Chief Justice"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Oldest mountain range in India?", options: ["Himalayas", "Aravallis", "Satpuras", "Vindhyas"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Which Article abolishes Untouchability?", options: ["Article 14", "Article 17", "Article 19", "Article 21"], answerIndex: 1, category: "GK", level: 3 },
    { text: "First Indian Sound Film?", options: ["Raja Harishchandra", "Alam Ara", "Mughal-e-Azam", "Mother India"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Who wrote 'Gitanjali'?", options: ["Premchand", "Tagore", "Naidu", "Nehru"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Largest organ of UN?", options: ["Security Council", "General Assembly", "Secretariat", "ICJ"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Satyameva Jayate is taken from?", options: ["Rigveda", "Mundaka Upanishad", "Ramayana", "Mahabharata"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Blue Revolution is related to?", options: ["Fish", "Milk", "Crops", "Oil"], answerIndex: 0, category: "GK", level: 3 },
    { text: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Currency of Russia?", options: ["Euro", "Ruble", "Dollar", "Pound"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Nobel Prize is given in how many fields?", options: ["5", "6", "4", "7"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Who was the 'Bird Man of India'?", options: ["Salim Ali", "Jim Corbett", "M.S. Swaminathan", "Verghese Kurien"], answerIndex: 0, category: "GK", level: 3 },
    { text: "Highest dam in India?", options: ["Bhakra Nangal", "Tehri", "Hirakud", "Sardar Sarovar"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Which state is the 'Spice Garden of India'?", options: ["Tamil Nadu", "Kerala", "Karnataka", "Assam"], answerIndex: 1, category: "GK", level: 3 },
    { text: "First IIT was set up in?", options: ["Bombay", "Kharagpur", "Kanpur", "Madras"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Who gave the theory of Relativity?", options: ["Newton", "Einstein", "Hawking", "Galileo"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Capital of Canada?", options: ["Toronto", "Ottawa", "Vancouver", "Montreal"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Project Tiger started in year?", options: ["1972", "1973", "1980", "1990"], answerIndex: 1, category: "GK", level: 3 },
    { text: "What is 'Black Gold'?", options: ["Coal", "Petroleum", "Gold", "Diamond"], answerIndex: 1, category: "GK", level: 3 },
    { text: "City known as 'Manchester of India'?", options: ["Mumbai", "Ahmedabad", "Surat", "Kanpur"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Silicon Valley of World is in?", options: ["New York", "California (USA)", "London", "Tokyo"], answerIndex: 1, category: "GK", level: 3 },
    { text: "Study of Universe?", options: ["Cosmology", "Astrology", "Geology", "Theology"], answerIndex: 0, category: "GK", level: 3 },
    { text: "Which country has no capital?", options: ["Nauru", "Vatican", "Monaco", "Singapore"], answerIndex: 0, category: "GK", level: 3 }, // Nauru actually doesn't have an official one
    { text: "Founder of Facebook?", options: ["Gates", "Zuckerberg", "Bezos", "Musk"], answerIndex: 1, category: "GK", level: 3 },

    // --- HISTORY (30 Questions) ---
    { text: "Indus Valley Civilization was?", options: ["Iron Age", "Bronze Age", "Stone Age", "Copper Age"], answerIndex: 1, category: "History", level: 3 },
    { text: "Founder of Maurya Dynasty?", options: ["Ashoka", "Chandragupta Maurya", "Bindusara", "Bimbisara"], answerIndex: 1, category: "History", level: 3 },
    { text: "Who wrote 'Akbarnama'?", options: ["Birbal", "Abul Fazl", "Faizi", "Todarmal"], answerIndex: 1, category: "History", level: 3 },
    { text: "Battle of Haldighati was fought in?", options: ["1526", "1556", "1576", "1761"], answerIndex: 2, category: "History", level: 3 },
    { text: "Permanent Settlement was introduced by?", options: ["Cornwallis", "Hastings", "Wellesley", "Dalhousie"], answerIndex: 0, category: "History", level: 3 },
    { text: "First Session of INC was held at?", options: ["Calcutta", "Bombay", "Madras", "Surat"], answerIndex: 1, category: "History", level: 3 },
    { text: "Partition of Bengal took place in?", options: ["1905", "1906", "1911", "1919"], answerIndex: 0, category: "History", level: 3 },
    { text: "Leader of Bardoli Satyagraha?", options: ["Gandhi", "Patel", "Nehru", "Azad"], answerIndex: 1, category: "History", level: 3 },
    { text: "Who called Subhash Chandra Bose 'Netaji'?", options: ["Gandhi", "Hitler/German Officials", "Nehru", "Tagore"], answerIndex: 1, category: "History", level: 3 },
    { text: "Cabinet Mission came to India in?", options: ["1942", "1945", "1946", "1947"], answerIndex: 2, category: "History", level: 3 },
    { text: "Purna Swaraj resolution was passed in?", options: ["1929 (Lahore)", "1930", "1931", "1942"], answerIndex: 0, category: "History", level: 3 },
    { text: "Who founded the 'Servants of India Society'?", options: ["Tilak", "Gokhale", "Ranade", "Annie Besant"], answerIndex: 1, category: "History", level: 3 },
    { text: "Megasthenes visited the court of?", options: ["Ashoka", "Chandragupta Maurya", "Harsha", "Vikramaditya"], answerIndex: 1, category: "History", level: 3 },
    { text: "Second Battle of Panipat?", options: ["1526", "1556", "1761", "1576"], answerIndex: 1, category: "History", level: 3 },
    { text: "Who was the 'Grand Old Man of India'?", options: ["Gandhi", "Dadabhai Naoroji", "Tilak", "Gokhale"], answerIndex: 1, category: "History", level: 3 },
    { text: "System of Dual Government in Bengal ended by?", options: ["Clive", "Warren Hastings", "Cornwallis", "Wellesley"], answerIndex: 1, category: "History", level: 3 },
    { text: "Founder of Khalji Dynasty?", options: ["Alauddin", "Jalaluddin", "Mubarak", "Khusrau"], answerIndex: 1, category: "History", level: 3 },
    { text: "Who built the Buland Darwaza?", options: ["Shah Jahan", "Akbar", "Jahangir", "Aurangzeb"], answerIndex: 1, category: "History", level: 3 },
    { text: "Treaty of Seringapatam was signed by?", options: ["Hyder Ali", "Tipu Sultan", "Nizam", "Marathas"], answerIndex: 1, category: "History", level: 3 },
    { text: "Who started the newspaper 'Kesari'?", options: ["Gandhi", "Tilak", "Nehru", "Bose"], answerIndex: 1, category: "History", level: 3 },
    { text: "First Governor General of Bengal?", options: ["Clive", "Hastings", "Cornwallis", "Bentinck"], answerIndex: 1, category: "History", level: 3 },
    { text: "Lucknow Pact (1916) was between?", options: ["INC and Muslim League", "INC and British", "Gandhi and Ambedkar", "Moderates and Extremists"], answerIndex: 0, category: "History", level: 3 },
    { text: "Who was the political guru of Subhash Bose?", options: ["Gandhi", "C.R. Das", "Tilak", "Gokhale"], answerIndex: 1, category: "History", level: 3 },
    { text: "Battle of Buxar year?", options: ["1757", "1764", "1761", "1857"], answerIndex: 1, category: "History", level: 3 },
    { text: "Vernacular Press Act was passed by?", options: ["Lytton", "Ripon", "Curzon", "Dufferin"], answerIndex: 0, category: "History", level: 3 },
    { text: "Who established the Ramakrishna Mission?", options: ["Ramakrishna", "Vivekananda", "Sarada Devi", "Dayanand"], answerIndex: 1, category: "History", level: 3 },
    { text: "Goa was liberated from Portuguese in?", options: ["1947", "1950", "1961", "1965"], answerIndex: 2, category: "History", level: 3 },
    { text: "Who wrote 'Arthashastra'?", options: ["Kautilya (Chanakya)", "Megasthenes", "Kalidasa", "Visakhadatta"], answerIndex: 0, category: "History", level: 3 },
    { text: "Capital of Harsha's empire?", options: ["Pataliputra", "Kannauj", "Thanesar", "Ujjain"], answerIndex: 1, category: "History", level: 3 },
    { text: "Operation Flood is related to?", options: ["Water", "Milk Production", "Flood Control", "Fish"], answerIndex: 1, category: "History", level: 3 },
];
