export const level1Questions = [
    // --- HEALTH (30 Questions) ---
    { text: "How should you sneeze to avoid spreading germs?", options: ["Into your hands", "Into your elbow", "Into the air", "Don't sneeze"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Which food is good for strong bones?", options: ["Candy", "Milk", "Soda", "Chips"], answerIndex: 1, category: "Health", level: 1 },
    { text: "How many glasses of water should you drink daily?", options: ["1-2", "3-4", "8-10", "20-30"], answerIndex: 2, category: "Health", level: 1 },
    { text: "What protects your head when riding a bike?", options: ["Hat", "Helmet", "Cap", "Hoodie"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Which of these is a vegetable?", options: ["Apple", "Carrot", "Banana", "Grape"], answerIndex: 1, category: "Health", level: 1 },
    { text: "When should you brush your teeth?", options: ["Once a week", "Every morning and night", "Only when they hurt", "Never"], answerIndex: 1, category: "Health", level: 1 },
    { text: "What does exercise do for your body?", options: ["Makes you tired only", "Makes you weak", "Makes you strong and healthy", "Makes you sick"], answerIndex: 2, category: "Health", level: 1 },
    { text: "Which is a healthy snack?", options: ["French Fries", "Fruit Salad", "Chocolate Bar", "Donut"], answerIndex: 1, category: "Health", level: 1 },
    { text: "What should you do before eating apples?", options: ["Wash them", "Cook them", "Paint them", "Freeze them"], answerIndex: 0, category: "Health", level: 1 },
    { text: "Which organ pumps blood?", options: ["Lungs", "Brain", "Heart", "Stomach"], answerIndex: 2, category: "Health", level: 1 },
    { text: "Too much sugar is bad for your?", options: ["Hair", "Teeth", "Nails", "Ears"], answerIndex: 1, category: "Health", level: 1 },
    { text: "What helps you see clearly?", options: ["Vitamin A (Carrots)", "Vitamin C (Oranges)", "Sugar", "Salt"], answerIndex: 0, category: "Health", level: 1 },
    { text: "What is the best drink for a hot day?", options: ["Hot Chocolate", "Water", "Salty Soup", "Oil"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Sleep helps your body to?", options: ["Shrink", "Recover and Grow", "Disappear", "Freeze"], answerIndex: 1, category: "Health", level: 1 },
    { text: "What happens if you don't wash hands?", options: ["You get super powers", "You get germs and sick", "You get taller", "Nothing"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Which of these is junk food?", options: ["Spinach", "Burger", "Apple", "Rice"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Doctors measure your temperature with?", options: ["Ruler", "Thermometer", "Scale", "Clock"], answerIndex: 1, category: "Health", level: 1 },
    { text: "The heart is located in your?", options: ["Head", "Chest", "Leg", "Arm"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Which activity is good for your heart?", options: ["Sitting all day", "Running", "Sleeping 24 hours", "Thinking"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Mosquito bites can cause?", options: ["Dengue", "Happiness", "Strength", "Hunger"], answerIndex: 0, category: "Health", level: 1 },
    { text: "What should you put on a small cut?", options: ["Dirt", "Band-aid", "Water only", "Paper"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Why do we wear seatbelts?", options: ["Fashion", "Safety", "To sleep", "To hold pants"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Sunscreen protects your?", options: ["Eyes", "Skin", "Teeth", "Bones"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Breakfast is the ____ meal of the day.", options: ["Last", "Most important", "Worst", "Sad"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Germs are?", options: ["Big animals", "Tiny living things that make you sick", "Toys", "Plants"], answerIndex: 1, category: "Health", level: 1 },
    { text: "You have two ____?", options: ["Hearts", "Kidneys", "Noses", "Mouths"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Which fruit has a lot of Vitamin C?", options: ["Banana", "Orange", "Apple", "Grapes"], answerIndex: 1, category: "Health", level: 1 },
    { text: "To keep lungs healthy, you should avoid?", options: ["Fresh air", "Smoke", "Exercise", "Water"], answerIndex: 1, category: "Health", level: 1 },
    { text: "Yoga is good for?", options: ["Fighting", "Flexibility and Mind", "Sleeping", "Eating"], answerIndex: 1, category: "Health", level: 1 },
    { text: "What protects your eyes from sun?", options: ["Umbrella", "Sunglasses", "Gloves", "Boots"], answerIndex: 1, category: "Health", level: 1 },

    // --- SCIENCE (30 Questions) ---
    { text: "What comes down but never goes up?", options: ["Rain", "Smoke", "Rocket", "Balloon"], answerIndex: 0, category: "Science", level: 1 },
    { text: "Which animal lives in water?", options: ["Cat", "Fish", "Dog", "Bird"], answerIndex: 1, category: "Science", level: 1 },
    { text: "What shape is the Earth?", options: ["Flat", "Square", "Round (Sphere)", "Triangle"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Which season is the hottest?", options: ["Winter", "Summer", "Monsoon", "Spring"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Ice melts into?", options: ["Gas", "Water", "Solid", "Steam"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Which animal gives us wool?", options: ["Cow", "Sheep", "Dog", "Cat"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Birds have ____ to fly.", options: ["Fins", "Wings", "Hands", "Wheels"], answerIndex: 1, category: "Science", level: 1 },
    { text: "A baby dog is called?", options: ["Kitten", "Puppy", "Cub", "Calf"], answerIndex: 1, category: "Science", level: 1 },
    { text: "What do cows eat?", options: ["Meat", "Grass", "Fish", "Eggs"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Which color absorbs the most heat?", options: ["White", "Black", "Blue", "Yellow"], answerIndex: 1, category: "Science", level: 1 },
    { text: "How many legs does a butterfly have?", options: ["4", "6", "8", "2"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Rainbows appear after?", options: ["Snow", "Rain", "Wind", "Night"], answerIndex: 1, category: "Science", level: 1 },
    { text: "The moon shines because?", options: ["It has a bulb", "It reflects Sun's light", "It is on fire", "It is magic"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Which is a domestic animal?", options: ["Lion", "Tiger", "Cow", "Bear"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Spiders spin what?", options: ["Wool", "Webs", "Cotton", "Plastic"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Fish breathe through?", options: ["Nose", "Gills", "Ears", "Mouth"], answerIndex: 1, category: "Science", level: 1 },
    { text: "A tadpole grows into a?", options: ["Fish", "Frog", "Lizard", "Snake"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Which is the fastest land animal?", options: ["Lion", "Cheetah", "Horse", "Rabbit"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Magnets attract?", options: ["Wood", "Plastic", "Iron", "Paper"], answerIndex: 2, category: "Science", level: 1 },
    { text: "What is the source of solar energy?", options: ["Moon", "Sun", "Earth", "Fire"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Which bird cannot fly?", options: ["Crow", "Parrot", "Ostrich", "Eagle"], answerIndex: 2, category: "Science", level: 1 },
    { text: "What do lungs do?", options: ["Pump blood", "Digest food", "Help us breathe", "Think"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Which planet has rings?", options: ["Mars", "Saturn", "Venus", "Mercury"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Water boils at?", options: ["50°C", "0°C", "100°C", "200°C"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Which is the largest ocean?", options: ["Indian", "Atlantic", "Pacific", "Arctic"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Honey comes from?", options: ["Wasps", "Bees", "Flies", "Ants"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Leaves are usually which color?", options: ["Red", "Blue", "Green", "Black"], answerIndex: 2, category: "Science", level: 1 },
    { text: "The sun rises in the?", options: ["West", "North", "East", "South"], answerIndex: 2, category: "Science", level: 1 },
    { text: "Camels have a ____?", options: ["Horn", "Hump", "Trunk", "Shell"], answerIndex: 1, category: "Science", level: 1 },
    { text: "Who invented the light bulb?", options: ["Einstein", "Newton", "Edison", "Tesla"], answerIndex: 2, category: "Science", level: 1 },

    // --- SPORTS (30 Questions) ---
    { text: "Cricket is played with?", options: ["Bat and Ball", "Stick and Puck", "Racket and Ball", "Foot and Ball"], answerIndex: 0, category: "Sports", level: 1 },
    { text: "Which sport happens in a pool?", options: ["Running", "Swimming", "Jumping", "Cycling"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Football is also called?", options: ["Rugby", "Soccer", "Tennis", "Golf"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "How many players in a Chess game?", options: ["1", "2", "4", "11"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "What do you hit in Tennis?", options: ["Shuttlecock", "Ball", "Puck", "Birdie"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "The Olympics are held every ____ years.", options: ["2", "3", "4", "5"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Which game creates a 'Checkmate'?", options: ["Ludo", "Chess", "Carrom", "Monopoly"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Mary Kom is a famous?", options: ["Singer", "Boxer", "Dancer", "Runner"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "In Football, who can touch the ball with hands?", options: ["Striker", "Defender", "Goalkeeper", "Referee"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Badminton uses a?", options: ["Ball", "Shuttlecock", "Puck", "Disc"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Running a very long distance is called?", options: ["Sprint", "Marathon", "Walk", "Jog"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "A century in cricket means ____ runs.", options: ["50", "10", "100", "200"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Which country invented Karate?", options: ["China", "India", "Japan", "USA"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Which game uses a heavy ball and 10 pins?", options: ["Bowling", "Cricket", "Tennis", "Golf"], answerIndex: 0, category: "Sports", level: 1 },
    { text: "Virat Kohli plays?", options: ["Tennis", "Cricket", "Football", "Hockey"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "How many rings on Olympic flag?", options: ["3", "4", "5", "6"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Basketball is played with?", options: ["Feet", "Hands", "Bat", "Racket"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "National Sport of India?", options: ["Cricket", "Hockey", "Football", "Kabaddi"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Neeraj Chopra throws?", options: ["Ball", "Disc", "Javelin", "Hammer"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Which card game has a King and Queen?", options: ["Uno", "Poker/Cards", "Monopoly", "Ludo"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "What do you wear to play football?", options: ["Skates", "Cleats/Shoes", "Flippers", "Heels"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Table Tennis is also called?", options: ["Ping Pong", "Tik Tak", "Ding Dong", "Tennis"], answerIndex: 0, category: "Sports", level: 1 },
    { text: "Kabaddi is played by?", options: ["Running", "Holding breath and tagging", "Kicking ball", "Hitting ball"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Who is the 'Flying Sikh'?", options: ["Milkha Singh", "Dhoni", "Kohli", "Tendulkar"], answerIndex: 0, category: "Sports", level: 1 },
    { text: "Where is Cricket World Cup final often played?", options: ["Court", "Stadium", "Pool", "Ring"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Goal is related to?", options: ["Cricket", "Football", "Tennis", "Chess"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Wrestling is done in a?", options: ["Pitch", "Court", "Ring", "Pool"], answerIndex: 2, category: "Sports", level: 1 },
    { text: "Pau Gasol plays?", options: ["Basketball", "Cricket", "Football", "Tennis"], answerIndex: 0, category: "Sports", level: 1 },
    { text: "Cycling involves?", options: ["Car", "Bike/Bicycle", "Bus", "Train"], answerIndex: 1, category: "Sports", level: 1 },
    { text: "Skiing is done on?", options: ["Water", "Sand", "Snow", "Grass"], answerIndex: 2, category: "Sports", level: 1 },

    // --- GK (30 Questions) ---
    { text: "Who is the Prime Minister of India?", options: ["Manmohan Singh", "Narendra Modi", "Rahul Gandhi", "Amit Shah"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which is the smallest state in India?", options: ["Goa", "Assam", "Bihar", "Odhisa"], answerIndex: 0, category: "GK", level: 1 },
    { text: "Capital of India?", options: ["Mumbai", "Delhi", "Kolkata", "Chennai"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which month comes after March?", options: ["May", "April", "June", "February"], answerIndex: 1, category: "GK", level: 1 },
    { text: "How many wheels does a tricycle have?", options: ["2", "3", "4", "1"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which direction does the sun rise?", options: ["North", "South", "East", "West"], answerIndex: 2, category: "GK", level: 1 },
    { text: "What do you use to cut paper?", options: ["Knife", "Scissors", "Spoon", "Fork"], answerIndex: 1, category: "GK", level: 1 },
    { text: "How many letters in English alphabet?", options: ["20", "21", "26", "25"], answerIndex: 2, category: "GK", level: 1 },
    { text: "Baby of a cat is?", options: ["Puppy", "Kitten", "Calf", "Foal"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which vehicle moves on tracks?", options: ["Car", "Bus", "Train", "Bike"], answerIndex: 2, category: "GK", level: 1 },
    { text: "Who delivers letters?", options: ["Doctor", "Postman", "Police", "Teacher"], answerIndex: 1, category: "GK", level: 1 },
    { text: "The national anthem of India is?", options: ["Vande Mataram", "Jana Gana Mana", "Sare Jahan Se Acha", "Maa Tujhe Salaam"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which is the National Bird of India?", options: ["Parrot", "Peacock", "Eagle", "Crow"], answerIndex: 1, category: "GK", level: 1 },
    { text: "How many days in a week?", options: ["30", "12", "7", "365"], answerIndex: 2, category: "GK", level: 1 },
    { text: "What is the capital of USA?", options: ["New York", "Washington D.C.", "Los Angeles", "Chicago"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Most spoken language in the world?", options: ["English", "Mandarin", "Hindi", "Spanish"], answerIndex: 0, category: "GK", level: 1 },
    { text: "Who teaches in a school?", options: ["Doctor", "Teacher", "Engineer", "Driver"], answerIndex: 1, category: "GK", level: 1 },
    { text: "National Animal of India?", options: ["Lion", "Tiger", "Elephant", "Horse"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Currency of India?", options: ["Dollar", "Rupee", "Yen", "Euro"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which is a flightless bird?", options: ["Sparrow", "Ostrich", "Eagle", "Pigeon"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Where do fish live?", options: ["Tree", "Water", "Sky", "Cave"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Which part of computer is the 'Brain'?", options: ["Monitor", "Keyboard", "CPU", "Mouse"], answerIndex: 2, category: "GK", level: 1 },
    { text: "A person who flies a plane is?", options: ["Driver", "Pilot", "Sailor", "Chef"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Who mends shoes?", options: ["Cobbler", "Tailor", "Barber", "Painter"], answerIndex: 0, category: "GK", level: 1 },
    { text: "How many colors in the Indian Flag?", options: ["2", "3", "4", "5"], answerIndex: 1, category: "GK", level: 1 }, // Technically 3 + blue chakra
    { text: "Festival of Lights is?", options: ["Holi", "Diwali", "Eid", "Christmas"], answerIndex: 1, category: "GK", level: 1 },
    { text: "Santa Claus comes on?", options: ["Diwali", "Holi", "Christmas", "Eid"], answerIndex: 2, category: "GK", level: 1 },
    { text: "Which is the tallest animal?", options: ["Tiger", "Giraffe", "Elephant", "Zebra"], answerIndex: 1, category: "GK", level: 1 },
    { text: "We smell with our?", options: ["Ears", "Eyes", "Nose", "Tongue"], answerIndex: 2, category: "GK", level: 1 },
    { text: "10 + 5 equals?", options: ["10", "15", "20", "50"], answerIndex: 1, category: "GK", level: 1 },

    // --- HISTORY (30 Questions) ---
    { text: "Who was the first Prime Minister of India?", options: ["Gandhi", "Nehru", "Patel", "Modi"], answerIndex: 1, category: "History", level: 1 },
    { text: "Taj Mahal is in which city?", options: ["Delhi", "Jaipur", "Agra", "Mumbai"], answerIndex: 2, category: "History", level: 1 },
    { text: "Gandhiji is on which currency note?", options: ["Dollar", "Indian Rupee", "Euro", "Yen"], answerIndex: 1, category: "History", level: 1 },
    { text: "Who is the Father of the Nation?", options: ["Nehru", "Gandhiji", "Bose", "Ambedkar"], answerIndex: 1, category: "History", level: 1 },
    { text: "When is Independence Day?", options: ["Jan 26", "Aug 15", "Oct 2", "Nov 14"], answerIndex: 1, category: "History", level: 1 },
    { text: "Red Fort is in?", options: ["Agra", "Delhi", "Mumbai", "Kolkata"], answerIndex: 1, category: "History", level: 1 },
    { text: "Who built the Taj Mahal?", options: ["Akbar", "Shah Jahan", "Babur", "Humayun"], answerIndex: 1, category: "History", level: 1 },
    { text: "Jhansi Ki Rani was defined by her?", options: ["Cooking", "Bravery", "Dancing", "Writing"], answerIndex: 1, category: "History", level: 1 },
    { text: "Which British Queen ruled India?", options: ["Elizabeth I", "Victoria", "Mary", "Anne"], answerIndex: 1, category: "History", level: 1 },
    { text: "Where was Gandhiji born?", options: ["Delhi", "Porbandar", "Mumbai", "Chennai"], answerIndex: 1, category: "History", level: 1 },
    { text: "Ashoka Chakra has how many spokes?", options: ["12", "24", "20", "15"], answerIndex: 1, category: "History", level: 1 },
    { text: "Ancient Egyptians built?", options: ["Castles", "Pyramids", "Skyscrapers", "Dams"], answerIndex: 1, category: "History", level: 1 },
    { text: "Great Wall is in?", options: ["India", "America", "China", "Japan"], answerIndex: 2, category: "History", level: 1 },
    { text: "The first man on Moon?", options: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Rakesh Sharma"], answerIndex: 1, category: "History", level: 1 },
    { text: "Shivaji Maharaj was a king of?", options: ["Mughals", "Marathas", "Rajputs", "Cholas"], answerIndex: 1, category: "History", level: 1 },
    { text: "Columbus discovered?", options: ["India", "America", "China", "Africa"], answerIndex: 1, category: "History", level: 1 }, // Traditional answer
    { text: "Who wrote our National Anthem?", options: ["Bankim Chandra", "Rabindranath Tagore", "Sarojini Naidu", "Premchand"], answerIndex: 1, category: "History", level: 1 },
    { text: "Republic Day is on?", options: ["Aug 15", "Jan 26", "Oct 2", "Nov 14"], answerIndex: 1, category: "History", level: 1 },
    { text: "Which leader is called 'Chacha'?", options: ["Gandhi", "Nehru", "Patel", "Bose"], answerIndex: 1, category: "History", level: 1 },
    { text: "Golden Temple is in?", options: ["Delhi", "Amritsar", "Mumbai", "Agra"], answerIndex: 1, category: "History", level: 1 },
    { text: "Oldest Veda?", options: ["Rigveda", "Samaveda", "Yajurveda", "Atharvaveda"], answerIndex: 0, category: "History", level: 1 },
    { text: "Qutub Minar is in?", options: ["Mumbai", "Delhi", "Agra", "Jaipur"], answerIndex: 1, category: "History", level: 1 },
    { text: "Which king had 9 gems (Navratnas)?", options: ["Akbar", "Aurangzeb", "Babur", "Shah Jahan"], answerIndex: 0, category: "History", level: 1 },
    { text: "Alexander the Great was from?", options: ["Rome", "Greece/Macedonia", "Egypt", "China"], answerIndex: 1, category: "History", level: 1 },
    { text: "Who fought with a sword?", options: ["Soldiers of old", "Modern police", "Doctors", "Scientists"], answerIndex: 0, category: "History", level: 1 },
    { text: "Statue of Unity is of?", options: ["Gandhi", "Nehru", "Sardar Patel", "Bose"], answerIndex: 2, category: "History", level: 1 },
    { text: "Who was the first President?", options: ["Nehru", "Rajendra Prasad", "Ambedkar", "Gandhi"], answerIndex: 1, category: "History", level: 1 },
    { text: "India became free in?", options: ["1947", "1950", "1942", "1930"], answerIndex: 0, category: "History", level: 1 },
    { text: "Mother Teresa helped the?", options: ["Rich", "Poor and Sick", "Kings", "Soldiers"], answerIndex: 1, category: "History", level: 1 },
    { text: "Who painted the Mona Lisa?", options: ["Picasso", "Da Vinci", "Van Gogh", "Husain"], answerIndex: 1, category: "History", level: 1 },
];
